### ISSUE TITLE
measure_polish_source_code.py

### ISSUE THREAD

**Issue by wanglongxingtianxia** [CodeEditorBench/CodeEditorBench#5]
measure_polish_source_code.py： Why are the model_id values in this file's SQL statement (45, 46, 47, 48)?

**Comment by mkj3085003** [comment]
model_id(45,46,47,48) is the standard code under the four scenarios problem for getting the correct outputs with the given inputs, and for calculating polish_limit. 
<img width="377" alt="32f3d7c2bce47563d2654708f9586d8" src="https://github.com/CodeEditorBench/CodeEditorBench/assets/93718766/081870fa-ddb6-4637-ad47-2ffd91fef453">
