### ISSUE TITLE
After the evaluation is complete pass@1 is 0

### ISSUE THREAD

**Issue by kartikzheng** [CodeEditorBench/CodeEditorBench#7]
Hello, I was testing code_debug capability of CodeLlama-13b-Instruct-hf. After the evaluation is complete, the query database statistics is 0.

`SELECT COUNT(*)
FROM solution s
JOIN problem p ON s.problem_id = p.problem_id
WHERE s.model_id = 61 AND (s.result < 4 OR s.result = 14);`
![图片4](https://github.com/CodeEditorBench/CodeEditorBench/assets/6856754/33e1b9a7-83f6-4987-ab00-72d152ace255)

During this period, it is also seen that there is normal in the evaluation.
![图片1](https://github.com/CodeEditorBench/CodeEditorBench/assets/6856754/d204da0d-04e9-4c9f-8d86-b6e0ffdd6fca)
![图片2](https://github.com/CodeEditorBench/CodeEditorBench/assets/6856754/c710b47e-9062-4d7d-a0bb-fc07adb70d0a)

If python3 compute_metrics.py is executed, pass@k is 0. What is going on?
![图片3](https://github.com/CodeEditorBench/CodeEditorBench/assets/6856754/0a1d546f-138c-4833-9d7d-3c19299547cf)

**Comment by mkj3085003** [comment]
Try to see a result for each solution,the specific meaning of each result number is given in the md, and have a look at the specific error messages in the log folder. 
You can give some of them in screenshots and I'll be happy to help you figure out the problem.

**Comment by kartikzheng** [comment]
@mkj3085003 Thank you for your reply. View solutions are mainly 10 and 11. Attached is data generated by CodeLlama-13b-Instruct-hf.

**Comment by Jiawei-Guo** [comment]
It appears there are both runtime and compilation errors. Have you processed the data post-inference, such as extracting generated code from the output and applying corresponding code language templates? Alternatively, could you share some of the results that need evaluation?

**Comment by kartikzheng** [comment]
[CodeLlama_13b_Instruct_hf_0_end.zip](https://github.com/CodeEditorBench/CodeEditorBench/files/15330405/CodeLlama_13b_Instruct_hf_0_end.zip)
@Jiawei-Guo Hello, I am following the tutorial operation, no additional processing. Attached is the result generated by the model. You can try to evaluate it to see if the same situation will occur. Thank you very much.

**Comment by Jiawei-Guo** [comment]
![image](https://github.com/CodeEditorBench/CodeEditorBench/assets/74909365/5e7ef6a6-3953-4278-bc74-0484e66b061e)
@kartikzheng It appears that you haven't executed the result_postprocess.py file, resulting in the code not being extracted from the output.We seem to have deleted this one by mistake when we updated the md file, sorry about that!

**Comment by kartikzheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/74909365/331081798-5e7ef6a6-3953-4278-bc74-0484e66b061e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mjg3MzEsIm5iZiI6MTcxNTkyODQzMSwicGF0aCI6Ii83NDkwOTM2NS8zMzEwODE3OTgtNWU3ZWY2YTYtMzk1My00Mjc4LWJjNzQtMDQ4NGU2NmIwNjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA2NDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1M2FjNjkxOGNkYTUzN2NlNWY2NzJhYzA3NzBkNTZmZmVkNTg2M2M2NGI0YjVmY2FlZmZhMGMyZGU5YzhmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3swMJ7VkJdukGwe0L2xojkhoqf2id_gO38pR9M_PSpk) @kartikzheng It appears that you haven't executed the result_postprocess.py file, resulting in the code not being extracted from the output. We seem to have deleted this one by mistake when we updated the md file, sorry about that!

Thank you for your reply. I tried post-processing, but the result is still the same. I found the same problem as this issue #8

**Comment by Jiawei-Guo** [comment]
@kartikzheng Have you mapped the results of your experiments after inference to docker?
![image](https://github.com/CodeEditorBench/CodeEditorBench/assets/74909365/d3b02cf6-340f-4660-80d3-895ca6f22111)

**Comment by Jiawei-Guo** [comment]
We've verified that our docker itself executes with no problems

**Comment by Jiawei-Guo** [comment]
<img width="896" alt="image" src="https://github.com/CodeEditorBench/CodeEditorBench/assets/74909365/b7591110-e631-4a65-9df1-1bce689546e5">
@kartikzheng We tested the results you provided(CodeLlama_13b_Instruct_hf_0_end.zip) and after post-processing, we mapped the file into the docker and followed the instructions of Evaluation's reademe to finally get the results.It looks like you've had a few unnecessary problems in executing the total process.

**Comment by AnitaLiu98** [comment]
Hello @kartikzheng,

We have conducted an evaluation using the JSONL file you provided. The results are as follows: the pass rate for Plus is 0.168 and for Primary it is 0.366. 

There are some points worth noting during the evaluation process that might cause errors in the judging results:

1. As described in [this README](https://github.com/CodeEditorBench/CodeEditorBench/blob/main/evaluation/README.md), to ensure the code can be properly evaluated, you should first execute `python3 add_template.py` to add templates to the code. Here is the output file we obtained after adding the templates:
   [CodeLlama_13b_Instruct_hf_0_end.jsonl.zip](https://github.com/CodeEditorBench/CodeEditorBench/files/15468297/CodeLlama_13b_Instruct_hf_0_end.jsonl.zip)

2. Additionally, you need to download the data from [this link](https://drive.google.com/file/d/1sC2cksEOmWMGK9k0zF_Rluh62ivEF7Po/view?usp=sharing) and place it in the `judge` folder (`judge/data`).

3. Finally, please ensure your machine has sufficient resources to conduct the evaluation. You can adjust the number of concurrent judge clients by reducing the `OJ_RUNNING` value in `/home/judge/etc/judge.conf`. Then restart the judge service with `pkill -f judge` and `nohup bash run_judge.sh > runlog.out 2>&1 &` and reset the result of your model to 0 in the database to restart the evaluation.

**Comment by kartikzheng** [comment]
@Jiawei-Guo @AnitaLiu98 Thanks for your reply. I will test it as soon as possible according to your suggestion.

**Comment by ywq2001** [comment]
I use the correct answers of the data set for evaluation, why does pass@1 not seem to reach 1? Is this normal? Sometimes, there will be wrong answers evaluated

**Comment by ywq2001** [comment]
![f3cd9decdc866b9dfb6e5bf709b6e36](https://github.com/CodeEditorBench/CodeEditorBench/assets/143774034/6b8deefa-0bab-42e9-bba0-835def084988)

**Comment by SwayamInSync** [comment]
> <img alt="image" width="896" src="https://private-user-images.githubusercontent.com/74909365/334335213-b7591110-e631-4a65-9df1-1bce689546e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTExODEsIm5iZiI6MTcyMTg5MDg4MSwicGF0aCI6Ii83NDkwOTM2NS8zMzQzMzUyMTMtYjc1OTExMTAtZTYzMS00YTY1LTlkZjEtMWJjZTY4OTU0NmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDA3MDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYjBkMjU2NDQ3Y2UwMThmZDE1MWI5NWFhOWQ2ZmRlYjE5OGMwZDc5OTE2YjYzMzAxYzkwNmM5ZTU2ZjYyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.51Fx2wDMgzhwTSkOkvot2OZwwlp8aeXp3NYBedFoVQc"> @kartikzheng We tested the results you provided(CodeLlama_13b_Instruct_hf_0_end.zip) and after post-processing, we mapped the file into the docker and followed the instructions of Evaluation's reademe to finally get the results.It looks like you've had a few unnecessary problems in executing the total process.

Hi @Jiawei-Guo I used the same generations provided by @kartikzheng but I am getting different results,
Plus: 0
Primary: 0.28

Is there any extra modifications with docker you are using than available on hub?

**Comment by SwayamInSync** [comment]
Ran the experiment again and same result
```
60 CodeLlama_13b_Instruct_hf_0_end
category: code_debug
category solution num:
 938
pass@1: 0.000
{'model_name': ['CodeLlama_13b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [938], 'passed_num': [0], 'code_debug': [0.0], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
60 CodeLlama_13b_Instruct_hf_0_end
category: code_debug
category solution num:
 1907
pass@1: 0.283
{'model_name': ['CodeLlama_13b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [1907], 'passed_num': [540], 'code_debug': [0.2831672784478238], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
```

**Comment by SwayamInSync** [comment]
> Ran the experiment again and same result
> 
> ```
> 60 CodeLlama_13b_Instruct_hf_0_end
> category: code_debug
> category solution num:
>  938
> pass@1: 0.000
> {'model_name': ['CodeLlama_13b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [938], 'passed_num': [0], 'code_debug': [0.0], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
> 60 CodeLlama_13b_Instruct_hf_0_end
> category: code_debug
> category solution num:
>  1907
> pass@1: 0.283
> {'model_name': ['CodeLlama_13b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [1907], 'passed_num': [540], 'code_debug': [0.2831672784478238], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
> ```

It shows `category num solutions` for Primary is 1907 and upon checking the number of entries in `/processed_solution/CodeLlama_13b_Instruct_hf_0_end.jsonl` it is giving 1908 (considering top row for metadata).

Does this mean the generation entries for `Plus` task are not in generation files?

cc: @kartikzheng

**Comment by SwayamInSync** [comment]
I tried generation and evaluation of CodeLlama-7B-Instruct and from the results it seems that the evaluation for PLUS is not happening
```
60 CodeLlama_7b_Instruct_hf_0_end
category: code_debug
category solution num:
938
pass@1: 0.000
{'model_name': ['CodeLlama_7b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [938], 'passed_num': [0], 'code_debug': [0.0], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
60 CodeLlama_7b_Instruct_hf_0_end
category: code_debug
category solution num:
1907
pass@1: 0.263
{'model_name': ['CodeLlama_7b_Instruct_hf_0_end'], 'model_id': [60], 'solution_num': [1907], 'passed_num': [501], 'code_debug': [0.2627163083377032], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
```

Attaching this table for reference
- Initially
```
mysql> SELECT result, COUNT(*) FROM solution GROUP BY result;
+--------+----------+
| result | COUNT(*) |
+--------+----------+
|      0 |     1907 |
|      4 |     7957 |
|      6 |        4 |
+--------+----------+
3 rows in set (0.00 sec)
```
- After evaluation
```
mysql> SELECT result, COUNT(*) FROM solution GROUP BY result;
+--------+----------+
| result | COUNT(*) |
+--------+----------+
|      4 |     8458 |
|      6 |      281 |
|      7 |        3 |
|      9 |        1 |
|     10 |      698 |
|     11 |      427 |
+--------+----------+
6 rows in set (0.00 sec)
```
