### ISSUE TITLE
There seems to be some problem with the evaluation process.

### ISSUE THREAD

**Issue by young-chao** [CodeEditorBench/CodeEditorBench#8]
I strictly followed the steps in [READEME.md](https://github.com/CodeEditorBench/CodeEditorBench/blob/main/evaluation/README.md) for inference and evaluation, however the score I got was 0. I suspect that the repository is still not rigorously tested at the moment, and I hope the author can make a reliable unit test, at least for The model mentioned in the inference script.

Inference:
```
#!/bin/bash
base_model="/data-cfs/Models/Original/OpenCodeInterpreter-DS-33B"
dataset="code_debug"
python vllm_inference.py \
    --base_model "$base_model" \
    --dataset "$dataset" \
    --input_data_dir "./data/" \
    --output_data_dir "./greedy_result/" \
    --batch_size 64 \
    --num_of_sequences 1 \
    --num_gpus 8 \
    --prompt_type "zero" \
    --start_idx 0 \
    --end_idx -1
```

Evaluation：
```
cd /home/judge/scripts
python add_template.py
python submit_solution.py

nohup bash run_judge.sh > runlog.out 2>&1 &

bash mysql.sh

select model_id,model_name from models where model_id>48;

UPDATE solution so
join (
select s.solution_id,s.result
from solution s
join models m on s.model_id=m.model_id
where model_name='OpenCodeInterpreter_DS_33B_0_end'
) AS subquery ON so.solution_id = subquery.solution_id
SET so.result = 0;

SELECT COUNT(*)
FROM solution s
JOIN problem p ON s.problem_id = p.problem_id
WHERE s.model_id = 'OpenCodeInterpreter_DS_33B_0_end' AND (s.result < 4 OR s.result = 14);

python compute_metrics.py
```
The results：
```
63 OpenCodeInterpreter_DS_33B_0_end
category: code_debug
category solution num:
 54
pass@1: 0.000
{'model_name': ['OpenCodeInterpreter_DS_33B_0_end'], 'model_id': [63], 'solution_num': [54], 'passed_num': [0], 'code_debug': [0.0], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
63 OpenCodeInterpreter_DS_33B_0_end
category: code_debug
category solution num:
 92
pass@1: 0.000
{'model_name': ['OpenCodeInterpreter_DS_33B_0_end'], 'model_id': [63], 'solution_num': [92], 'passed_num': [0], 'code_debug': [0.0], 'code_translation': [None], 'code_requirement_switch': [None], 'code_polishment': [None], 'polish_score_total': [nan]}
```

**Comment by young-chao** [comment]
The results after inference were post-processed, and I confirmed that the generated java code could indeed be compiled successfully. I am not clear about the generated path and verification process, and some steps still confuse me. I don't want to spend too much time understanding the entire process. After all, my purpose is to use this benchmark rather than recreate a benchmark.

**Comment by Jiawei-Guo** [comment]
@young-chao I apologize for the inconvenience. Our evaluation was initially conducted using a locally built OJ system, which may introduce various issues when transitioning to Docker. We'll reproduce the process and provide you with a more straightforward evaluation script.

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！

**Comment by Jiawei-Guo** [comment]
@young-chao Have you mapped the results of your experiments after inference to docker?
![image](https://github.com/CodeEditorBench/CodeEditorBench/assets/74909365/5bc43b81-6d55-4005-9622-d8d8423d086c)

**Comment by Jiawei-Guo** [comment]
We've verified that our docker itself executes with no problems
